package customErrors

import "errors"

var (
	ErrAuthorizationHeaderMissing = errors.New("authorization header missing")
	ErrDatabase                   = errors.New("database error")
	ErrEmailAlreadyRegistered     = errors.New("email already registered")
	ErrInvalidAuthorizationFormat = errors.New("invalid authorization format")
	ErrInvalidCredentials         = errors.New("invalid credentials")
	ErrInvalidEmailFormat         = errors.New("invalid email format")
	ErrInvalidInputFormat         = errors.New("invalid input format")
	ErrInvalidLoginData           = errors.New("invalid login data")
	ErrInvalidOrExpiredToken      = errors.New("invalid or expired token")
	ErrInvalidRoleFormat          = errors.New("invalid role format")
	ErrInvalidTokenClaims         = errors.New("invalid token claims")
	ErrInvalidTokenSignature      = errors.New("invalid token signature")
	ErrLoginProcess               = errors.New("login process failed")
	ErrPasswordProcessing         = errors.New("password processing failed")
	ErrRoleNotFoundInToken        = errors.New("role not found in token")
	ErrTokenExpired               = errors.New("token expired")
	ErrTokenGeneration            = errors.New("token generation failed")
	ErrTokenRefresh               = errors.New("token refresh failed")
	ErrTooManyRequests            = errors.New("too many requests")
	ErrTransactionCommit          = errors.New("transaction commit failed")
	ErrTransactionStart           = errors.New("transaction start failed")
	ErrUnauthorizedResourceAccess = errors.New("you are not authorized to access this resource")
	ErrUserCreation               = errors.New("user creation failed")
	ErrUserNotAuthenticated       = errors.New("user not authenticated")
	ErrUserNotFound               = errors.New("user not found")

	ErrInvalidPostData = errors.New("invalid post data")
	ErrPostCreation    = errors.New("post creation failed")
	ErrPostDelete      = errors.New("post delete failed")
	ErrPostId          = errors.New("post ID is required")
	ErrPostNotFound    = errors.New("post not found")
	ErrPostUpdate      = errors.New("post update failed")
)
