basePath: /
definitions:
  models.UserLoginFailureBadRequestResponse:
    properties:
      error:
        example: invalid login data
        type: string
    type: object
  models.UserLoginFailureInternalServerErrorResponse:
    properties:
      error:
        example: login process failed
        type: string
    type: object
  models.UserLoginFailureUnauthorizedResponse:
    properties:
      error:
        example: invalid credentials
        type: string
    type: object
  models.UserLoginRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - name
    - password
    type: object
  models.UserLoginSuccessResponse:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      token_type:
        type: string
    type: object
  models.UserLogoutFailureUnauthorizedResponse:
    properties:
      error:
        example: invalid or expired token
        type: string
    type: object
  models.UserLogoutSuccessResponse:
    properties:
      instructions:
        example: Please remove the token from your client storage
        type: string
      message:
        example: Successfully logged out
        type: string
    type: object
  models.UserRefreshTokenFailureServerErrorResponse:
    properties:
      error:
        example: token refresh failed
        type: string
    type: object
  models.UserRefreshTokenFailureUnauthorizedResponse:
    properties:
      error:
        example: invalid or expired token
        type: string
    type: object
  models.UserRefreshTokenSuccessResponse:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      token_type:
        type: string
    type: object
  models.UserRegisterFailureBadRequestResponse:
    properties:
      details:
        type: string
      error:
        example: invalid input format
        type: string
    type: object
  models.UserRegisterFailureConflictResponse:
    properties:
      error:
        example: email already registered
        type: string
    type: object
  models.UserRegisterFailureInternalServerErrorResponse:
    properties:
      error:
        example: password processing failed
        type: string
    type: object
  models.UserRegisterRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - name
    - password
    type: object
  models.UserRegisterSuccessResponse:
    properties:
      message:
        example: User registered successfully
        type: string
      user_id:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: your.email@example.com
    name: Roman
  description: API for a blog platform built with Go, Gin, GORM, JWT
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: ProBlog API
  version: "1.0"
paths:
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and get JWT token
      parameters:
      - description: User login data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserLoginSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.UserLoginFailureBadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.UserLoginFailureUnauthorizedResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.UserLoginFailureInternalServerErrorResponse'
      summary: User login
      tags:
      - auth
  /api/v1/logout:
    post:
      description: Logout user and invalidate tokens on client side
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserLogoutSuccessResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.UserLogoutFailureUnauthorizedResponse'
      security:
      - ApiKeyAuth: []
      summary: Logout user
      tags:
      - auth
  /api/v1/profile:
    get:
      description: Retrieve logged-in user's profile information
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Get user profile
      tags:
      - user
  /api/v1/refresh-token:
    post:
      description: Generate a new JWT token using a valid refresh token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserRefreshTokenSuccessResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.UserRefreshTokenFailureUnauthorizedResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.UserRefreshTokenFailureServerErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Refresh JWT token
      tags:
      - auth
  /api/v1/register:
    post:
      consumes:
      - application/json
      description: Register a new user with email and password
      parameters:
      - description: User registration data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserRegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.UserRegisterSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.UserRegisterFailureBadRequestResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.UserRegisterFailureConflictResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.UserRegisterFailureInternalServerErrorResponse'
      summary: Register new user
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
